name: Generate ASCII Artwork

on:
  push:

jobs:
  ascii-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Cowsay Program
        uses: sudo apt-get install cowsay -y

      - name: Execute Cowsay CMD
        run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

      - name: Test Files Exists
        run: grep -i "dragon" dragon.txt

      - name: Read Files
        run: cat dragon.txt

      - name: Checkout Repo Files
        uses: ls
