name: Exploring Variables and Secrets

on:
  schedule:
    - cron: "*/1 * * * *"

  # push:

env:
  CONTAINER_REGISTRY: docker.io
  DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
  IMAGE_NAME: github-actions-nginx
jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Docker Build
        run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest


      - name: Docker Login
        run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}


      - name: Docker Publish
        run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Deploy App
        run: echo "Deploying app to production server..."
